#
# Blog Settings
#


# Jekyll Settings
markdown: rdiscount
pygments: true
paginate: 6
paginate_path: /page:num
permalink: /:title
baseurl: /
#lsi: true

# Disqus Comments
disqus_short_name: hahaya
disqus_show_comment_count: true

# site
title: hahaya's blog
url: http://riqiang.github.io/blog/
feed: /atom.xml

# color scheme
highlight: light

# author
author_name: hahaya
author_email: hahayacoder@gmail.com
author_info: <a href="http://riqiang.github.io/blog">hahaya</a>

description: 
google_analytics: 
show_downloads: true
theme: jekyll-theme-time-machine